name: takyeef
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.2
  provider: ^4.0.5
  http: ^0.12.1
  font_awesome_flutter: ^8.8.1
  flutter_svg: ^0.17.4
  url_launcher: ^5.4.7
  flutter_linkify: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
   
    - images/worker.jpg
    - images/light_logo.png
  

  fonts:
    - family: Almarai
      fonts:
        - asset: fonts/Almarai-Regular.ttf




        
          
   